---
- name: Check if helm diff plugin is present
  ansible.builtin.shell: helm plugin list 2>/dev/null |grep ^diff
  register: helm_diff_plugin
  changed_when: false
  failed_when: "helm_diff_plugin.rc not in [ 0, 1 ]"

- name: Install helm diff
  ansible.builtin.shell: helm plugin install https://github.com/databus23/helm-diff
  when: not ansible_check_mode and helm_diff_plugin.rc != 0
