---
- name: Install helm prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gpg
      - git
    state: latest
    update_cache: false
    cache_valid_time: 86400
  tags:
    - helm_packages
    - apt_packages

- name: Install heml keyring
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /usr/share/keyrings/helm.asc
    mode: "0644"
  tags:
    - helm_repostitory
    - helm_repostitory_signature

- name: Add heml packages repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/helm.asc]
      https://baltocdn.com/helm/stable/debian/ all main
    state: present
  tags:
    - helm_repository

- name: Install helm
  ansible.builtin.apt:
    name: helm
    state: latest
    cache_valid_time: 86400
  # will fail in check mode if db isn't present
  when: not ansible_check_mode
  tags:
    - helm_install

- name: Configure bash autompletion for helm for all users
  ansible.builtin.template:
    src: helm-bash-autocompletion.j2
    dest: /etc/profile.d/helm.sh
    owner: root
    group: root
    mode: '0755'
  tags:
    - helm_bashrc
