---
- name: Install helm
  ansible.builtin.include_tasks:
    file: helm.yml
    apply:
      tags: [helm]
  tags: [helm]

- name: Install helm diff
  ansible.builtin.include_tasks:
    file: helm_diff.yml
    apply:
      tags: [helm, helm_diff]
  tags: [helm, helm_diff]
